name: CI

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'README.md'
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.x]
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install dependencies
        run: npm install
      - name: Lint (se disponível)
        run: |
          if [ -f .eslintrc.js ] || [ -f .eslintrc.json ] || [ -f .eslintrc ]; then
            npx eslint .
          else
            echo 'No ESLint config found, skipping lint.'
          fi
      - name: Run build (checa sintaxe dos arquivos principais)
        run: |
          node --check index.js
          node --check src/main.js
          node --check src/services/llmService.js
          node --check src/services/newsService.js
          node --check src/utils/persistence.js
          node --check src/utils/logger.js
          node --check src/providers/llmProviderFactory.js
          node --check src/providers/openaiProvider.js
          node --check src/providers/geminiProvider.js
          node --check src/providers/ollamaProvider.js
      - name: Run tests (Jest + coverage)
        run: npm test -- --coverage
