name: CI

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'README.md'
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Install dependencies
        run: npm install
      - name: Run build (checa se o projeto builda sem erros)
        run: |
          node --check index.js
          node --check src/main.js
          node --check src/services/llmService.js
          node --check src/services/newsService.js
          node --check src/utils/persistence.js
          node --check src/utils/logger.js
          node --check src/providers/llmProviderFactory.js
          node --check src/providers/openaiProvider.js
          node --check src/providers/geminiProvider.js
          node --check src/providers/ollamaProvider.js
      - name: Run tests
        run: npm test -- --coverage
      - name: Get coverage percent
        id: coverage
        run: |
          if [ -f ./coverage/coverage-summary.json ]; then
            COVERAGE=$(node -e "console.log(Math.round(require('./coverage/coverage-summary.json').total.lines.pct || 0))")
          else
            COVERAGE=0
          fi
          # Define cor do badge
          if [ "$COVERAGE" -ge 80 ]; then
            BADGE_COLOR=brightgreen
          elif [ "$COVERAGE" -ge 50 ]; then
            BADGE_COLOR=yellow
          else
            BADGE_COLOR=red
          fi
          echo "COVERAGE=$COVERAGE" >> $GITHUB_ENV
          echo "BADGE_COLOR=$BADGE_COLOR" >> $GITHUB_ENV
      - name: Update README coverage badge
        run: |
          # Remove todas as linhas com badge de coverage
          sed -i '/coverage-.*%25-.*\.svg)/Id' README.md
          # Adiciona na segunda linha
          sed -i "2i ![Coverage](https://img.shields.io/badge/coverage-${COVERAGE}%25-${BADGE_COLOR}.svg)" README.md
          head -10 README.md
        env:
          COVERAGE: ${{ env.COVERAGE }}
          BADGE_COLOR: ${{ env.BADGE_COLOR }}
      - name: Commit badge if changed
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add README.md
          git diff --cached --quiet || git commit -m "ci: update test badge"
          git push https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }}.git HEAD:main
