name: CI

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'README.md'
  pull_request:
    branches: [ main ]

jobs:
  test:
    if: ${{ !contains(github.event.head_commit.message, 'ci: update test badge') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm test
      - name: Update README badge
        if: always()
        run: |
          STATUS=$(if [ $? -eq 0 ]; then echo "PASS"; else echo "FAIL"; fi)
          sed -i '/^![Tests]/d' README.md
          sed -i '1i \\[Tests](https://img.shields.io/badge/tests-'$STATUS'-'$([ "$STATUS" = "PASS" ] && echo "brightgreen" || echo "red")'.svg)' README.md
      - name: Commit badge if changed
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add README.md
          git diff --cached --quiet || git commit -m "ci: update test badge"
          git push https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }}.git HEAD:main
