name: CI

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'README.md'
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Install dependencies
        run: npm install
      - name: Run build (checa se o projeto builda sem erros)
        run: |
          node --check index.js
          node --check src/main.js
          node --check src/services/llmService.js
          node --check src/services/newsService.js
          node --check src/utils/persistence.js
          node --check src/utils/logger.js
          node --check src/providers/llmProviderFactory.js
          node --check src/providers/openaiProvider.js
          node --check src/providers/geminiProvider.js
          node --check src/providers/ollamaProvider.js
      - name: Run tests
        run: npm test -- --coverage
      - name: Get coverage percent
        id: coverage
        run: |
          if [ -f ./coverage/coverage-summary.json ]; then
            COVERAGE=$(node -e "console.log(require('./coverage/coverage-summary.json').total.lines.pct)")
          else
            COVERAGE=0
          fi
          echo "COVERAGE=$COVERAGE" >> $GITHUB_ENV
      - name: Update README coverage badge
        run: |
          COVERAGE="${COVERAGE:-0}"
          sed -i '/^![Coverage]/Id' README.md
          sed -i "2i ![Coverage](https://img.shields.io/badge/coverage-${COVERAGE}%25-brightgreen.svg)" README.md
          cat README.md | head -10
        env:
          COVERAGE: ${{ env.COVERAGE }}
      - name: Commit badge if changed
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add README.md
          git diff --cached --quiet || git commit -m "ci: update test badge"
          git push https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }}.git HEAD:main
